### ISSUE TITLE
users can access any sliders (even out of their scope)

### ISSUE THREAD

**Issue by ak4t0sh** [limsko/moodle-filter_slider#6]
**Steps to reproduce**

As administrator

- Create a course "A" and add a block_slider in it with few slides. Get the slideid.
- Create a course "B" and add a forum.
- Create an user "Bob" and enrol it in course B (ensure he is NOT enrol in course A)

As "Bob"

- Enter course B > Forum
- Add a discussion with content [SLIDER-slideid] and save

**Expected** 
As the block is out of his scope bob should not see the slider at all.

**Actual**
Slider is loading almost normally. Thanks to Moodle API images are not loaded but users can see all titles or url provided in course B.

In a filter you can not control what an user is typing and sliderid are easily guessable - and as you know "never trust the user input" :) - so  during display process you have check if current user is allow to see this slider.

**Comment by limsko** [comment]
Fixed in new version of plugin. Thanks for Your work on testing the plugin.
